# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:
  name: Default
  #demands: Agent.ComputerName -equals WENCHM18VM
  demands: 
  - Agent.ComputerName -equals ADRMS #WENCHM462VM
  - Agent.Name -equals ADRMSI

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  System.Debug: true
steps:
- task: Cache@2
  inputs:
    key: 'CacheMisssTest | "$(Agent.OS)" | package.json'
#    restoreKeys: |
#       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm